from typing import Protocol, Mapping, Any

class ImageProvider(Protocol):
    name: str
    def generate(self, prompt: str, *, seed: int, references: list[str]) -> Mapping[str, Any]: ...
class AnimationProvider(Protocol):
    name: str
    def animate(self, image_uri: str, *, duration_seconds: float, seed: int) -> Mapping[str, Any]: ...
class InputAdapter(Protocol):
    kinds: frozenset[str]
    def normalize(self, source: str) -> Mapping[str, Any]: ...
class SheetAdapter(Protocol):
    def publish(self, project_id: str, rows: Mapping[str,list[dict]]) -> None: ...
class DriveAdapter(Protocol):
    def provision(self, project_id: str) -> Mapping[str,str]: ...
