import {useEffect, useState, type FormEvent} from 'react';

type Session = {username:string;csrf:string};
type Project = {id:string;name:string;state:string;version:number};
type Artifact = {id:number;scene_id:number|null;kind:string;sha256:string;status:string;version:number};
type Scene = {id:number;code:string;start_ms:number;end_ms:number;text:string;state:string;qa_state:string;approval_state:string};
type Detail = {project:Project;scenes:Scene[];artifacts:Artifact[];audio:null|{duration_ms:number};script:string|null;history:{id:number;type:string;created_at:string}[];jobs:{id:number;kind:string;state:string}[];next_actions:string[];gates:Record<string,{current:boolean}>;limits:{upload_bytes:number}};
const labels:Record<string,string> = {ACTIVE:'Đang hoạt động',PAUSED:'Tạm dừng',BLOCKED:'Cần xử lý',COMPLETED:'Hoàn tất',PLANNED:'Đã lập cảnh',REQUIRED:'Cần duyệt',NOT_REQUIRED:'Không bắt buộc',APPROVED:'Đã duyệt',REJECTED:'Đã từ chối',PENDING:'Chờ kiểm tra',PASSED:'Đạt',FAILED:'Không đạt',IMAGE_READY:'Có ảnh',QUEUED:'Đang chờ',RUNNING:'Đang chạy',SUCCEEDED:'Thành công',pause:'Tạm dừng',resume:'Tiếp tục',plan:'Lập kế hoạch cảnh',checkpoint:'Lưu điểm kiểm tra',pilot:'Cảnh thí điểm',post_batch:'Toàn bộ ảnh',final:'Video cuối',NARRATION:'Giọng đọc',PROJECT_CREATED:'Tạo dự án',SCRIPT_SOURCE_IMPORTED:'Nhập kịch bản',NARRATION_MEASURED:'Đo giọng đọc WAV',SRT_IMPORTED:'Nhập phụ đề',SCENES_PLANNED:'Lập kế hoạch cảnh',CHECKPOINT_CREATED:'Lưu điểm kiểm tra'};
Object.assign(labels,{DRAFT:'Bản nháp',READY:'Sẵn sàng',STALE:'Cần cập nhật',INVALIDATED:'Đã mất hiệu lực',SUPERSEDED:'Đã thay thế',CANCELLED:'Đã hủy',NONE:'Chưa có',NOT_STARTED:'Chưa bắt đầu',NOT_CHECKED:'Chưa kiểm tra',PASS:'Đạt',FAIL:'Không đạt',PAUSED_PROJECT:'Tạm dừng dự án',PROJECT_PAUSED:'Tạm dừng dự án',PROJECT_RESUMED:'Tiếp tục dự án',DOCUMENT_IMPORTED:'Nhập kịch bản',CHECKPOINT_SAVED:'Lưu điểm kiểm tra',IMAGE:'Ảnh',VIDEO:'Video',PROMPT:'Lời nhắc tạo ảnh'});
const label = (v:string) => labels[v]||v;
const time = (ms:number) => `${(ms/1000).toLocaleString('vi-VN',{maximumFractionDigits:3})} giây`;

export default function App(){
 const [session,setSession]=useState<Session|null>(null), [boot,setBoot]=useState(true), [projects,setProjects]=useState<Project[]>([]), [selected,setSelected]=useState(''), [detail,setDetail]=useState<Detail|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('inputs'),[creating,setCreating]=useState(false);
 async function api(path:string, options:RequestInit={}){
  let response:Response;
  try { response=await fetch('/api'+path,{...options,headers:{...(options.body instanceof Blob?{}:{'Content-Type':'application/json'}),...(session?{'X-CSRF-Token':session.csrf}:{}),...options.headers}}); }
  catch { throw new Error('Mất kết nối. Kiểm tra mạng rồi thử lại; dữ liệu đã nhập vẫn được giữ nguyên.'); }
  const value=await response.json().catch(()=>({detail:response.status===413?'Tệp quá lớn. Chọn WAV tối đa 64 MiB; TXT và SRT tối đa 1 MiB.':'Máy chủ chưa phản hồi hợp lệ. Vui lòng thử lại sau.'}));
  if(!response.ok){if(response.status===401)setSession(null);throw new Error(value.detail||'Không thể kết nối. Vui lòng thử lại.');}
  return value;
 }
 async function refresh(pid=selected){
  const list=await api('/projects');setProjects(list.projects);
  if(pid)setDetail(await api('/projects/'+pid));
 }
 useEffect(()=>{api('/session').then(setSession).catch(()=>{}).finally(()=>setBoot(false));},[]);
 useEffect(()=>{if(session)refresh().catch(e=>setError(e.message));},[session]);
 useEffect(()=>{setDetail(null);if(selected&&session)api('/projects/'+selected).then(setDetail).catch(e=>setError(e.message));},[selected]);
 async function run(task:()=>Promise<void>,success:string){setBusy(true);setError('');setMessage('');try{await task();setMessage(success);}catch(e){setError(e instanceof Error?e.message:'Không thể xử lý yêu cầu.');}finally{setBusy(false);}}
 function signIn(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);run(async()=>{setSession(await api('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(data))}));},'Đã đăng nhập.');}
 function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);run(async()=>{const result=await api('/projects',{method:'POST',body:JSON.stringify({name:data.get('name'),min_scenes:Number(data.get('min')),max_scenes:Number(data.get('max'))})});await refresh(result.id);setSelected(result.id);setCreating(false);},'Đã tạo dự án. Hãy nhập kịch bản và giọng đọc.');}
 async function action(name:string){if(name==='plan'&&detail?.scenes.length&&!confirm('Lập lại cảnh sẽ thu hồi bằng chứng và duyệt phụ thuộc. Tiếp tục?'))return;await run(async()=>{await api(`/projects/${selected}/actions/${name}`,{method:'POST',body:JSON.stringify({note:name==='checkpoint'?'Điểm kiểm tra do chủ sở hữu lưu trên web':''})});await refresh();},name==='resume'?'Đã tiếp tục dự án. Không tự chạy tác vụ AI.':'Đã ghi nhận thao tác và cập nhật trạng thái.');}
 function upload(kind:string,file:File){run(async()=>{await api(`/projects/${selected}/uploads/${kind}`,{method:'POST',body:file});await refresh();},'Đã nhập dữ liệu và kiểm tra bằng hệ thống.');}
 if(boot)return <main className="login"><p role="status">Đang kiểm tra phiên đăng nhập…</p></main>;
 if(!session)return <main className="login"><section className="login-brand"><div className="brandmark">a.</div><p className="eyebrow">AUDIOBOOKS STUDIO</p><h1>Mỗi câu chuyện,<br/>một quy trình rõ ràng.</h1><p>Quản lý kịch bản, giọng đọc, phân cảnh và các điểm duyệt trong một không gian làm việc riêng tư.</p><span className="pill">Xưởng kể chuyện · Dành cho chủ sở hữu</span></section><section className="login-card"><p className="eyebrow">KHÔNG GIAN RIÊNG TƯ</p><h2>Đăng nhập xưởng</h2><p className="muted">Tài khoản chủ sở hữu được quản trị viên khởi tạo trên máy chủ. Không có tài khoản mặc định.</p><form onSubmit={signIn}><label>Tên đăng nhập<input name="username" autoComplete="username" maxLength={80} required/></label><label>Mật khẩu<input name="password" type="password" autoComplete="current-password" maxLength={256} required/></label>{error&&<div role="alert" className="alert error">{error}</div>}<button disabled={busy} className="primary">{busy?'Đang xác thực…':'Vào không gian làm việc →'}</button></form><p className="footnote">Dữ liệu và tệp chỉ truy cập được sau khi đăng nhập.</p></section></main>;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/">a. <span>Audiobooks<small>XƯỞNG KỂ CHUYỆN</small></span></a><div className="sidebar-heading">KHÔNG GIAN LÀM VIỆC</div><button className={!selected?'nav active':'nav'} onClick={()=>{setSelected('');setCreating(false);}}>▦ Tổng quan dự án <b>{projects.length}</b></button><div className="sidebar-heading">DỰ ÁN GẦN ĐÂY</div><nav>{projects.slice(0,12).map(p=><button key={p.id} className={selected===p.id?'nav active':'nav'} onClick={()=>{setSelected(p.id);setCreating(false);setTab('inputs');}}>{p.name}</button>)}</nav><div className="owner"><span className="avatar">{session.username.charAt(0).toUpperCase()}</span><div><strong>{session.username}</strong><small>Chủ sở hữu</small></div><button aria-label="Đăng xuất" title="Đăng xuất" onClick={()=>run(async()=>{await api('/logout',{method:'POST'});setSession(null);setSelected('');setDetail(null);},'')}>↗</button></div></aside>
 <div className="workspace"><header><span>Không gian làm việc <span className="muted"> / {selected?'Chi tiết dự án':'Tổng quan'}</span></span><span className="private">● Riêng tư</span></header><main className="content">
 {error&&<div role="alert" className="alert error">{error}<button aria-label="Đóng thông báo lỗi" onClick={()=>setError('')}>×</button></div>}{message&&<div role="status" className="alert success">{message}</div>}{busy&&<p role="status" className="note">Đang xử lý yêu cầu… Vui lòng chờ.</p>}
 <div className="page-heading"><div><p className="eyebrow">XƯỞNG KỂ CHUYỆN</p><h1>{creating?'Tạo dự án mới':detail?.project.name||'Thư viện dự án'}</h1><p className="muted">{selected?'Đầu vào thật. Trạng thái thật. Mọi điểm duyệt được lưu lại.':'Từ giọng kể đến phân cảnh — theo dõi từng bước ở một nơi.'}</p></div><button disabled={busy} className="primary" onClick={()=>{setCreating(true);setSelected('');}}>＋ Tạo dự án</button></div>
 <div className="notice"><strong>Phạm vi phiên bản đầu</strong><span>Nhập kịch bản TXT, giọng đọc PCM WAV, phụ đề SRT và lập cảnh. Chưa tạo ảnh/giọng AI, chưa ghép video hoặc tạo hiệu ứng vẽ theo nét trên web. Không tự gọi nhà cung cấp.</span></div>
 {creating?<section className="panel narrow"><h2>Thiết lập câu chuyện</h2><form onSubmit={create}><label>Tên dự án<input name="name" maxLength={160} placeholder="Ví dụ: Những câu chuyện bên hiên nhà" required/></label><div className="form-grid"><label>Số cảnh tối thiểu<input name="min" type="number" defaultValue={50} min={1} max={360} required/></label><label>Số cảnh tối đa<input name="max" type="number" defaultValue={360} min={1} max={360} required/></label></div><p className="muted">Hệ thống chia cảnh từ thời gian phụ đề. Với tệp thử ngắn, giảm số cảnh tối thiểu xuống 1. Kịch bản không tự sinh thời gian hay giọng đọc.</p><div className="actions"><button disabled={busy} className="primary">Tạo dự án</button><button type="button" onClick={()=>setCreating(false)}>Hủy</button></div></form></section>:!selected?<><div className="stats"><section><small>TỔNG DỰ ÁN</small><strong>{projects.length}</strong></section><section><small>ĐANG HOẠT ĐỘNG</small><strong>{projects.filter(p=>p.state==='ACTIVE').length}</strong></section><section><small>CẦN CHÚ Ý</small><strong>{projects.filter(p=>['PAUSED','BLOCKED'].includes(p.state)).length}</strong></section></div><section className="panel"><div className="section-heading"><h2>Dự án của bạn</h2><button disabled={busy} onClick={()=>run(()=>refresh(),'Đã cập nhật danh sách.')}>↻ Làm mới</button></div>{!projects.length?<div className="empty"><div className="empty-icon">▤</div><h3>Bắt đầu bằng câu chuyện đầu tiên</h3><p>Tạo dự án, sau đó tải giọng đọc WAV và phụ đề khớp thời gian.</p><button className="primary" onClick={()=>setCreating(true)}>Tạo dự án đầu tiên</button></div>:<div className="project-list">{projects.map(p=><button className="project-row" key={p.id} onClick={()=>setSelected(p.id)}><div className="project-icon">▤</div><div><strong>{p.name}</strong><small>Phiên bản {p.version} · Tiếng Việt</small></div><span className={'badge '+p.state}>{label(p.state)}</span><span>→</span></button>)}</div>}</section></>:!detail?<div className="panel" role="status">Đang tải dữ liệu dự án…</div>:<>
 <div className="project-toolbar"><span className={'badge '+detail.project.state}>{label(detail.project.state)}</span><span className="muted">Phiên bản {detail.project.version} · {detail.scenes.length} cảnh</span><div className="actions">{detail.next_actions.map(a=><button key={a} disabled={busy} className={a==='plan'?'primary':''} onClick={()=>action(a)}>{label(a)}</button>)}<button disabled={busy} onClick={()=>run(()=>refresh(),'Đã cập nhật trạng thái.')}>↻ Làm mới</button></div></div>
 <div className="tabs" role="tablist">{[['inputs','01 · Đầu vào'],['scenes','02 · Phân cảnh'],['media','03 · Tệp & duyệt'],['history','04 · Lịch sử']].map(([id,text])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{text}</button>)}</div>
 {tab==='inputs'&&<div className="input-grid"><section className="panel"><h2>Nguồn kể chuyện</h2><p className="muted">Nhập theo thứ tự: kịch bản → giọng đọc → phụ đề. Thay đầu vào có thể làm mất hiệu lực kế hoạch và duyệt cũ.</p>{[['script','1','Kịch bản văn bản','TXT UTF-8, tối đa 1 MiB.','.txt'],['audio','2','Giọng đọc đã thu','PCM WAV không nén; tối đa '+Math.floor(detail.limits.upload_bytes/1048576)+' MiB.','.wav'],['subtitle','3','Phụ đề có thời gian','SRT UTF-8, tối đa 1 MiB; phải khớp giọng đọc.','.srt']].map(([kind,n,title,help,accept])=><div className="upload-row" key={kind}><span className="step">{n}</span><div><h3>{title}</h3><p>{help}</p><label className="file-label">Chọn tệp để nhập<input type="file" accept={accept} disabled={busy||detail.project.state!=='ACTIVE'} onChange={e=>{const f=e.target.files?.[0];if(f)upload(kind,f);e.target.value='';}}/></label></div></div>)}{busy&&<p role="status">Đang xử lý… Vui lòng không đóng trang hoặc gửi lại tệp.</p>}</section><section className="panel"><h2>Đầu vào đã ghi nhận</h2><dl><dt>Giọng đọc</dt><dd>{detail.audio?time(detail.audio.duration_ms)+' · Đo từ mẫu PCM':'Chưa nhập WAV'}</dd><dt>Kịch bản</dt><dd>{detail.script||'Chưa nhập văn bản'}</dd><dt>Kế hoạch</dt><dd>{detail.scenes.length?`${detail.scenes.length} cảnh đã lưu`:'Chưa lập cảnh. Nhập WAV và SRT trước.'}</dd></dl><div className="note">Nút “Lập kế hoạch cảnh” xuất hiện khi đã có giọng đọc và phụ đề. Lập cảnh là xử lý cục bộ, không phải sáng tác bằng AI.</div></section></div>}
 {tab==='scenes'&&<section className="panel"><h2>Danh sách phân cảnh</h2><p className="muted">Nội dung từ phụ đề và thời lượng do hệ thống tính. Duyệt không thể vượt qua yêu cầu QA/bằng chứng hiện hành.</p>{!detail.scenes.length?<div className="empty">Chưa có cảnh. Hoàn tất đầu vào và chọn “Lập kế hoạch cảnh”.</div>:<div className="scenes">{detail.scenes.map(s=><article className="scene" key={s.id}><div className="section-heading"><strong>{s.code}</strong><span className="muted">{time(s.start_ms)} → {time(s.end_ms)}</span></div><p>{s.text}</p><div className="scene-meta"><span className="badge">{label(s.state)}</span><span>Kiểm tra: {label(s.qa_state)}</span><span>Duyệt: {label(s.approval_state)}</span></div><div className="actions">{['APPROVED','REJECTED'].map(decision=><button disabled={busy||detail.project.state!=='ACTIVE'} key={decision} onClick={()=>{if(confirm('Xác nhận '+(decision==='APPROVED'?'duyệt':'từ chối')+' cảnh '+s.code+'? Pipeline sẽ kiểm tra bằng chứng trước khi ghi nhận.'))run(async()=>{await api(`/projects/${selected}/scenes/${s.id}/review`,{method:'POST',body:JSON.stringify({decision})});await refresh();},'Đã ghi nhận quyết định của chủ sở hữu.');}}>{decision==='APPROVED'?'Duyệt cảnh':'Từ chối cảnh'}</button>)}</div></article>)}</div>}</section>}
 {tab==='media'&&<><div className="stats">{Object.entries(detail.gates).map(([key,gate])=><section key={key}><small>{label(key)}</small><h3>{gate.current?'✓ Bằng chứng hiện hành':'Chưa đạt điểm duyệt'}</h3></section>)}</div><section className="panel"><h2>Tệp do pipeline quản lý</h2><p className="muted">Chỉ tệp đang hoạt động, đúng SHA-256 và nằm trong thư mục dự án mới được phục vụ. Trình duyệt có thể tải qua menu của bộ phát hoặc liên kết.</p>{!detail.artifacts.length?<div className="empty">Chưa có tệp. Nhập giọng đọc WAV để bắt đầu.</div>:detail.artifacts.map(a=><article className="artifact" key={a.id}><div className="section-heading"><h3>{label(a.kind)} #{a.id}</h3><span className="badge">{label(a.status)}</span></div><small>Phiên bản {a.version} · SHA-256</small><code>{a.sha256}</code>{a.status==='ACTIVE'&&<>{a.kind==='NARRATION'&&<audio controls preload="none" src={'/api/artifacts/'+a.id}/>}<a className="button" href={'/api/artifacts/'+a.id} target="_blank" rel="noreferrer">Mở / tải tệp ↗</a></>}</article>)}</section></>}
 {tab==='history'&&<div className="input-grid"><section className="panel"><h2>Nhật ký gần nhất</h2><p className="muted">Tối đa 100 sự kiện, mới nhất trước. Không tự khôi phục hoặc tiếp tục khi bấm lưu điểm kiểm tra.</p><ol className="timeline">{detail.history.map(e=><li key={e.id}><strong>{label(e.type)}</strong><time>{new Date(e.created_at).toLocaleString('vi-VN')}</time></li>)}</ol></section><section className="panel"><h2>Công việc trong pipeline</h2><p className="muted">Đây là trạng thái hệ thống, không có tác vụ nền tự chạy. Web chưa thực thi AI hay ghép video.</p>{!detail.jobs.length?<p>Chưa có công việc.</p>:detail.jobs.map(j=><p key={j.id}>#{j.id} · {label(j.kind)} <span className="badge">{label(j.state)}</span></p>)}</section></div>}
 </>}
 <footer>Audiobooks Studio · Dữ liệu riêng tư · Không tự động tạo nội dung hoặc vượt điểm duyệt</footer></main></div></div>;
}
